name: cuba_weather
description: Application for mobile devices of the Cuba Weather project implemented with Flutter

version: 1.4.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.1.0
  http: ^0.12.0
  equatable: ^1.0.0
  cuba_weather_dart: ^3.0.1
  shared_preferences: ^0.5.6
  autocomplete_textfield: ^1.7.3
  package_info: ^0.4.0+13
  url_launcher: ^5.4.1
  getflutter: ^1.0.0-dev.1
  weather_icons: ^2.0.0
  xml: ^3.7.0
  html: ^0.14.0+3
  share: ^0.6.3+5
  tuple: ^1.0.3
  font_awesome_flutter: ^8.5.0
  flutter_speed_dial: ^1.2.5
  geolocator: ^5.2.1
  intl:

flutter:

  uses-material-design: true

  assets:
    - images/
